### PR TITLE
Only wait for send status confirmation for unicasts

### PR DESCRIPTION
**Pull request by puddly**
This allows for the downstream application to send two consecutive group commands without waiting for a send confirmation for the first.

### CODE REVIEW

**Comment by TheJulianJES** [comment]
Changes seem to work as expected btw

**Comment by pipiche38** [comment]
I don't know how it works with ezsp, but my experience on zigate is that by relying on this we were exhausting internal resources PDUs
So it might be interesting to see the impact on large heavy network.
And many having an easy way to disable this

**Comment by puddly** [comment]
On EmberZNet the only effect is that you run into `NETWORK_BUSY` more quickly, which is expected since more group commands can be sent at once (e.g. group light color commands usually send `on()` + `move_to_color()`).

**Comment by pipiche38** [comment]
And which layer handle the NETWORK_BUSY issue ? Is zigpy will do the retry or is that the above layer ?

**Comment by puddly** [comment]
Bellows tries three times if it's a transient error: https://github.com/zigpy/bellows/blob/e700caf2a50454d0060c3fcd5f67f4b49ebfce46/bellows/zigbee/application.py#L760-L786

**Pull request merged**
