### PR TITLE
Update README.md list of compatible hardware

### PR DESCRIPTION
**Pull request by Hedda**
Update README.md list of compatible hardware

### CODE REVIEW

**Comment by MattWestb** [comment]
I is missing warning that Bitron Video/Smabit dont have one proofed working updated firmware (but i think its working with Mgenta/UPCs original firmware).

Also warning on Sonoff ZBB that its have stability problems then the SM-011 module / PCB hardware quality.

Also if putting in more device pleas updating the device in the Wiki and the firmware matrix if information is known.

My large question is if moving more dials to the Wiki and only have short comments in the main bellows (and other radio) front page and linking to detailed info in the wiki but its one Zigpy project policy question.

And one great thanks for updating and "cleaning" the Zigpy projects redme pages device sections !!!

**Comment by MattWestb** [comment]
Sorry was forgetting i is missing EByte-E180-Z120B that is in the Wiki.

**Comment by Hedda** [comment]
> I is missing warning that Bitron Video/Smabit dont have one proofed working updated firmware (but i think its working with Mgenta/UPCs original firmware).

It works with original firmware and there is no guides on how-to upgrade the firmware, see -> https://github.com/zigpy/bellows/issues/348

> Also warning on Sonoff ZBB that its have stability problems then the SM-011 module / PCB hardware quality.

I was chewed out by yourself when I wanted to add such a warning, see -> https://github.com/zigpy/bellows/pull/406

>  forgetting i is missing EByte-E180-Z120B that is in the Wiki.

OK I can add EByte E180-Z120B and EByte E180-Z120B-TB

**Comment by MattWestb** [comment]
I have no problem using Tasmota (I have not testing ESPHome but i like converting back to it) with WiFi and its normally not so bad and you is getting connecting problems in the log (have running one tuya / LIDL LED strips controller with EZSP 6.9.2.0 for some weeks now that is one MG21 and is very stable).

But the quality of Sonoff ZBB (and the SM-011 module and USB-stick) is more or less the same as no name CC-2531 dongles and the user shall not having to high expectations on this devices.

The most funny / sad i have reading was one user with one CC-2531 with external antenna that was not working at all and then switching to the PCB antenna it was possible communicating with all devices :-)) (but sad for the user).

Thanks for the EBytes !!! :-))

**Pull request merged**
