### PR TITLE
Feature efr32 support - EZSP v8 framing

### PR DESCRIPTION
**Pull request by bdrr77**
Hi,

I added the support for EZSP v8 framing which allows bellows to run against Silicon Labs EmberZNet SDK 6.7.6 (latest). EZSP v8 simply passes Frame ID field to a 16 bit value

I added it so it does not affect currently supported devices, but adapts to those that run a newer version of EZSP
I tested it over a Silicon Labs Thunderboard Sense 2 (EFR32MG12 based), for which I built a specific NCP firmware (bellows CLI commands tests only)

Best,
Brian

### CODE REVIEW

**Comment by Adminiuga** [comment]
I'll add some tests and merge it. 
Thanks

**Comment by bdrr77** [comment]
Hi sorry I did not get your comment
Feel free to discard the tests I edited

**Comment by Adminiuga** [comment]
Did you check if forming of the network works with bellows? I thought there were some changes and EZSP decision policies were replaced by a bit mask?

**Comment by Adminiuga** [comment]
Oops, missed the tests. Looks good

**Comment by Adminiuga** [comment]
ah, Lint checks were failing. Can you run the changed files through [black](https://pypi.org/project/black) and update the PR?

**Comment by bdrr77** [comment]
Just did the tests, committed the changes

**Comment by Adminiuga** [comment]
new isort sorts things differently.

**Comment by pedro11x** [comment]
> Hi,
> 
> I added the support for EZSP v8 framing which allows bellows to run against Silicon Labs EmberZNet SDK 6.7.6 (latest). EZSP v8 simply passes Frame ID field to a 16 bit value
> 
> I added it so it does not affect currently supported devices, but adapts to those that run a newer version of EZSP
> I tested it over a Silicon Labs Thunderboard Sense 2 (EFR32MG12 based), for which I built a specific NCP firmware (bellows CLI commands tests only)
> 
> Best,
> Brian
Can you send me the ncp firmware for the thuderboard? Thanks you

**Comment by bdrr77** [comment]
Hi,

Sorry for the time it took

Have a look in the releases here:
https://github.com/brian-silabs/ncp-uart-no-fc-115200

Best,
Brian

Le sam. 3 oct. 2020, à 23 h 51, Pedro Pacheco <notifications@github.com> a
écrit :

**Pull request merged**
