### PR TITLE
minor readme tweaks; added empty/shell contributing and getting-started

### PR DESCRIPTION
**Pull request by CanDoAnything**
edited the readme to put the format in compliance w/ the 
[markdownlint rules](https://github.com/DavidAnson/markdownlint/blob/master/doc/Rules.md)

### CODE REVIEW

**Comment by CanDoAnything** [comment]
also, i added two template files to be filled out/updated...i'd like to contribute, but not sure how to get started ;)

**Comment by Adminiuga** [comment]
> {what are your rules for contributions?}

Asking real questions here :) We don't have any rules at the moment??? Maybe guidelines? Let's say the guidelines:
1. code which is easy to understand has greater chance of being merged
2. we gonna ask questions about the code and why it was implemented in this "particular" way
3. code must have tests, as we'd like to keep coverage up

> {What branch should people do PRs to?}

[`dev`](https://github.com/zigpy/bellows) is the default branch so all PRs go against this branch


> {I assume unit tests should be required for any new /changed code}

Yes

**Comment by Adminiuga** [comment]
> # Getting Started
>
>## Basics
> {how do i get started using this? I see that Home assistant heavily relies on this library. I'd like to contribute}

Correct, ZHA component relies on a particular library handling Zigbee communication over a specific radio. Each radio relies (extends `ControllerApplication` class) on Zigpy library. 
How to get started? Start using HomeAssistant ZHA component, find the area which you'd like to improve and start tweaking the code i guess? 

https://www.youtube.com/playlist?list=PL-awFRrdECXvAs1mN2t2xaI0_bQRh2AqD could be a good primer if you don't have a prior zigbee exposure and would like to get better "under the hood" understanding

**Comment by Hedda** [comment]
Please also see the somewhat related pull request #204 (as well as #203 which is related to it)

**Comment by Hedda** [comment]
@CanDoAnything any chance you want to do the same format compliance job for Zigpy readme file?

https://github.com/zigpy/zigpy/blob/dev/README.md

and maybe also zigpy-xbee, zigpy-deconz and zigpy-zigate which are all intertwined projects too? 

https://github.com/zigpy/zigpy-xbee/blob/dev/README.md

https://github.com/zigpy/zigpy-deconz/blob/dev/README.md

https://github.com/doudz/zigpy-zigate/blob/master/README.md

**Pull request closed without merging**
