### PR TITLE
Add recommendation not to use WiFi based EZSP bridges to ITead Sonoff ZBBridge

### PR DESCRIPTION
**Pull request by Hedda**
Consider removing the Sonoff ZBBridge from bellows list of hardware as EZSP over WiFi-based bridges is now infamously unstable.

 - **_[ITEAD Sonoff ZBBridge](https://www.itead.cc/smart-home/sonoff-zbbridge.html) (Note! This first have to be flashed with [Tasmota firmware and EmberZNet firmware](https://www.digiblur.com/2020/07/how-to-use-sonoff-zigbee-bridge-with.html))_**

Argument is that having Sonoff ZBBridge listed in the readme file of bellows, which makes it read as equivalent to recommended hardware, is causing long-term harm to the reputation of zigpy and ZHA because many first-time users have a horrible experience with stability on it.

Currently, when zigpy and ZHA end-users ask for support with Sonoff ZBBridge they are told that they should cut their losses and instead buy a USB stick/dongle or an Ethernet (wired) bridge/gateway version instead if wanting to achieve a stable connection over EZSP between the Zigbee coordinator adapter and bellows/zigpy/ZHA. 

I believe that not having it listed here would at least make some users stop pointing their fingers bellows/zigpy/ZHA developers.

It might be stable enough for people who have extremely stable WiFi, but is it a product that should be advertised for zigpy/ZHA?

Maybe just list a few wired Ethernet bridges/gateways under compatible hardware instead? ...in a separate pull request of course.

PS: For reference; I was actually the one who originally added ITead Sonoff ZBBridge to the list via PR https://github.com/zigpy/bellows/pull/285 and https://github.com/zigpy/zigpy/pull/447

### CODE REVIEW

**Comment by Hedda** [comment]
FYI, Home Assistant ZHA and zigpy developers already strongly recommending not to use any WiFi based EZSP bridges/gateways:

https://github.com/zigpy/bellows#warning-about-zigbee-to-wifi-bridges

The reason Ember remote bridges over serial-to-IP proxy server is not recommended is that clients using the EZSP serial protocol requires a robust connection between the EmberZNet Zigbee stack running on EFR32 MCU and the serial port of the Zigbee radio. With solutions such as *ITEAD Sonoff ZBBridge* or a Ser2Net serial proxy connection over a WiFi network it is expected to see `NCP entered failed state. Requesting APP controller restart` in the logs. This is a normal part of the operation and indicates there was a drop in communication which caused packet loss to occurred between the zigpy radio library and the Zigbee radio. The use of serial network proxies/bridges/servers over WiFi is therefore not recommended when wanting a stable Zigbee environment with Silicon Labs Ember based Zigbee radios. The developers of the [bellows radio library for the zigpy project](https://github.com/zigpy/bellows) has more information about this if needed.

**Comment by MattWestb** [comment]
I dont agree !!

First Sonoff was having problems with the "EZSP Sonoff bug" that id fixed in EZSP 6.7.8.0. and then they was having some bad data settings in there firmware and have released one " EZSP 6.77.9.0 (that is one 6.7.8.0) that is fixing that.

If have one good stable WiFi Sonoff is working very well then looking how many is being used around in HA systems. And bellows is handling  comport problems very well and its being logged in HA log then having problem.

Compering with 2 other "supported coordinators":
TI CC-2531 Have large problems then its having to less  resources for runing more then around 20 devices and is corrupting its NVRAM and need being re flashed or erased.
Its also have problem with the com port cant being re initiated if its being loss in one docker container (that most HA user is using) and is one very low end device for beginners but perhaps too low  for at all being used in HA. Sonoff ZBB is one better start devices for new ZHA user that TI CC-2531 !!

CornBee I and II: Is around the same performance perhaps better FR part then the SM-011 module have bad configurated antenna filters. Must users having problem with USB 3 ports and other devices attached with USB that is braking the continuation.
And DE is recommending using one USB extension cable (that  is not delivered with the 40€ device) for getting it working at all !
And most users is using it in HA with docker and is having large problems then the device watchdog is restarting the device or its losing the com port and cant communicating with the stick until the container is restarted.

Using EZSP radios with GIPO UART or with socket bit with WiFi or Ethernet is working great and dont have the "docker comport connection problems" and also the WiFi is working better  for the moment that one USB connected radio that having problem with docker port mapping.

**Comment by MattWestb** [comment]
For my its better getting user feedback before removing one device that many user is using daily in there system and its one discussion of experiences of coordinator that can being used for getting feed  back https://github.com/zigpy/zigpy/discussions/576

Also "recommending" is little dangerous than all radio hardware have there good and bad side and its depends of the user experience and user case how its working for the user in the real world.

And the best is to collecting user experience so user an see how good / bad its working in real.

**Comment by Hedda** [comment]
> First Sonoff was having problems with the "EZSP Sonoff bug" that is fixed in EZSP 6.7.8.0. and then they was having some bad data settings in there firmware and have released one " EZSP 6.7.9.0 (that is one 6.7.8.0) that is fixing that.

EZSP 6.7.9.0 is not listed https://github.com/arendst/Tasmota/tree/development/tools/fw_SonoffZigbeeBridge_ezsp

Still, that can not solve issues with those people who do not have a 100% stable WiFi connection 24/7/365, and I think it would be unfair to go around telling all of those users to buy better WiFi hardware instead of recommending an other Zigbee HW solution. 

> An Headda do you have testing using one coordinator over WiFi like tasmota or ESPHome ?

Yes I have in the past used Sonoff ZBBridge by ITead flashed Tasmota with ZHA in Home Assistant but since switched to USB-sticks (first I moved to Elelabs USB adapter but have since moved to Electrolama's zzh, so I am currently now using bellows).

> And the best is to collecting user experience so user an see how good / bad its working in real.

Please do read all Sonoff Zigbee bridge stability complaints on HA's community forums -> https://community.home-assistant.io You see a lot of first time ZHA users are having a bad time with the Sonoff ZBBridge, most of which have later proven to be WiFi related.

**Comment by MattWestb** [comment]
> Know that EZSP 6.7.9.0 is not available https://github.com/arendst/Tasmota/tree/development/tools/fw_SonoffZigbeeBridge_ezsp
> 

Im very sorry but i cant saying to the tasmota devs wot they shall do or not but the supplier of the signed firmware have supplied one new firmware and is recommending it.
https://github.com/arendst/Tasmota/issues/10413#issuecomment-790274262
I have only seen one tasmota user trying it bit is more ZHA user that have doing it and its not have and new bugs and its also the same firmware they is using in the new USB stack but its not signed (is it one copy of Garys release ?)
And the tasmota devs is vers silent = no interest in the problem but have saying that EZSP 6.7.8.00 is working and have solving there problems.

> Still, that can not solve issues with those people who do not have a 100% stable WiFi connection 24/7/365, and I think it would be unfair to go around telling all of those users to buy better WiFi hardware instead of just recommending other Zigbee solutions.
> 
> Understand that a problem is that most other applications does not require a 100% stable WiFi solution so most users will not know/discover that their WiFi setup is not stable enough for Sonoff ZBBridge until after they already bought it.

WiFi is trying resending packages that is not being OK but its making the latency being larger that can being bad. But is you is having so bad WiFi you shall not using it for one HA system at all and that the user must realize and learning fixing that.
ZHA is doing one good work logging problems on the comport so its easy to diagnose and putting the  user on the right track.

> > An Headda do you have testing using one coordinator over WiFi like tasmota or ESPHome ?
> 
> Yes I have in the past used Sonoff ZBBridge by ITead flashed Tasmota with ZHA in Home Assistant but since switched to USB-sticks (first I moved to Elelabs USB adapter but have since moved to Electrolama's zzh, so I am currently now using bellows).

Then you is very likely being hitted of the docker comport problems that is one plague for all USB connected devices the last months.

> Note! Remember that this hardware recommendation is really aimed at new users and new at advanced/expert users like yourself.

I still its better putting user experience in the discussion so user can see wot is good and bad and can making there own decision and not black listing or recommending specific hardware !!

If you is living in US you need one good lawyer for getting you not paying users that  is being fucker up of bad recommendations.

**Comment by patrickfong** [comment]
While I don't disagree with your asssessment that beginner users or users with subpar wifi infrastructure may experience issues with wifi bridges, I would rather this be a warning to users rather than pulling support outright.

In my case I have spent a lot of time and effort upgrading the home wifi with multiple APs and dedicated controllers.  For some users it will make sense to us a wifi bridge (where the machine running ZHA is sitting in a closet with poor signal penetration).  The choice should be there for users rather than us making the decision for them.

**Comment by Hedda** [comment]
> While I don't disagree with your asssessment that beginner users or users with subpar wifi infrastructure may experience issues with wifi bridges, I would rather this be a warning to users rather than pulling support outright.

To clarify; I'm not suggesting support for it be removed in code, I only mean that WiFi-bridges should not be listed in the readme file.

**Comment by Hedda** [comment]
> While I don't disagree with your asssessment that beginner users or users with subpar wifi infrastructure may experience issues with wifi bridges, I would rather this be a warning to users rather than pulling support outright.
> 
> In my case I have spent a lot of time and effort upgrading the home wifi with multiple APs and dedicated controllers. For some users it will make sense to use a wifi bridge (where the machine running ZHA is sitting in a closet with poor signal penetration). The choice should be there for users rather than us making the decision for them.

**Comment by Hedda** [comment]
Update: Changed PR to just add a small note recommendation not to use WiFi-based EZSP bridges to ITead Sonoff ZBBridge:

- [ITead Sonoff ZBBridge](https://www.itead.cc/smart-home/sonoff-zbbridge.html) (Note! [**WiFi-based bridges are not recommended for zigpy/bellows with EZSP radios](https://github.com/home-assistant/home-assistant.io/issues/17170)**. Also, this first have to be flashed with [Tasmota firmware and Silabs EmberZNet NCP EZSP UART Host firmware to use as Serial-to-IP adapter](https://www.digiblur.com/2020/07/how-to-use-sonoff-zigbee-bridge-with.html))

**Comment by Hedda** [comment]
FYI, ZHA integration documentation for Home Assistant is now been updated with the same suggested "**_not recommended_**" note:

https://www.home-assistant.io/integrations/zha/#known-working-zigbee-radio-modules

* _ITead Sonoff ZBBridge (**Note! WiFi-based bridges are not recommended for ZHA with EZSP radios.** Also, this first have to be flashed with Tasmota firmware and Silabs EmberZNet NCP EZSP UART Host firmware to use as Serial-to-IP adapter)_

Again, we do not want to prevent anyone from using a Zigbee to WiFi bridge, but do not want to recommend them to new users.

Quote posted by @dmulcahey in https://github.com/zigpy/zigpy/discussions/584#discussioncomment-405356

> _We will not support wireless versions they will be use at your own risk. There is too much latency with wifi and they are too unpredictable. Look at all of the trouble folks are having with ZHA and the sonoff bridge. It’s a mess._

Quote posted by @dmulcahey in https://github.com/zigpy/zigpy/discussions/584#discussioncomment-406041

> _Sure, but you are adding another variable into support. This is not guaranteed to be like this on anyone else’s setup. ISP routers suck and most folks don’t know enough to configure their network for efficiency. This adds too much into the mix to support from my perspective. The Sonoff bridge has been a nightmare. Like I said, it will work, but we won’t spend a lot of time triaging any issues that arise when folks are using anything that is serial over WiFi._

**Comment by Hedda** [comment]
Closing and replacing with PR https://github.com/zigpy/bellows/pull/413

**Pull request closed without merging**
