### PR TITLE
Import CONF_NWK parameters to config

### PR DESCRIPTION
**Pull request by SylvainPer**
Allows network configuration at initialization without calling zigpy library

### CODE REVIEW

**Comment by Adminiuga** [comment]
You don't need it. Use ApplicationController.Schema to validate network configuration schema, so it stays consistent between different libraries

**Comment by SylvainPer** [comment]
It's not the validation that causes problem but the declaration.
Here the code I'm using that working with ZNP:

```python
import bellows.config as conf
config = {conf.CONF_DEVICE: {"path": serialPort, "baudrate": 115200}, conf.CONF_NWK: {}}
if set_extendedPanId != 0:
        config[conf.CONF_NWK][conf.CONF_NWK_EXTENDED_PAN_ID] = "%s" % (
            t.EUI64(t.uint64_t(set_extendedPanId).serialize())
        )
if set_channel != 0:
        config[conf.CONF_NWK][conf.CONF_NWK_CHANNEL] = set_channel
```

I can't do it the same way, what should I do ?

**Comment by Adminiuga** [comment]
You are already using `"path"` and `"baudrate"`, so you could use string literals for the rest of the config, or import those from zigpy. Zigpy is installed anyway as part of bellows dependency.

**Comment by SylvainPer** [comment]
Many thanks, it avoids several import (bellows and zigpy).

**Pull request merged**
